"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from petstore import Petstore, models
from tests.test_client import create_test_http_client


def test_store_get_inventory():
    test_http_client = create_test_http_client("getInventory")

    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("PETSTORE_API_KEY", "value"),
    ) as p_client:
        assert p_client is not None

        res = p_client.store.get_inventory()
        assert res is not None
        assert res == {
            "key": 111959,
            "key1": 333452,
            "key2": 973245,
        }


def test_store_place_order():
    test_http_client = create_test_http_client("placeOrder")

    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("PETSTORE_API_KEY", "value"),
    ) as p_client:
        assert p_client is not None

        res = p_client.store.place_order(
            request={
                "id": 10,
                "pet_id": 198772,
                "quantity": 7,
                "status": models.OrderStatus.APPROVED,
            }
        )
        assert res is not None
        assert res == models.Order(
            id=10,
            pet_id=198772,
            quantity=7,
            status=models.OrderStatus.APPROVED,
        )


def test_store_get_order_by_id():
    test_http_client = create_test_http_client("getOrderById")

    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("PETSTORE_API_KEY", "value"),
    ) as p_client:
        assert p_client is not None

        res = p_client.store.get_order_by_id(order_id=728529)
        assert res is not None
        assert res == models.Order(
            id=10,
            pet_id=198772,
            quantity=7,
            status=models.OrderStatus.APPROVED,
        )


def test_store_delete_order():
    test_http_client = create_test_http_client("deleteOrder")

    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("PETSTORE_API_KEY", "value"),
    ) as p_client:
        assert p_client is not None

        res = p_client.store.delete_order(order_id=690575)
        assert res is not None
        assert res == models.Order(
            id=10,
            pet_id=198772,
            quantity=7,
            status=models.OrderStatus.APPROVED,
        )
