"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from petstore import Petstore, models
from tests.test_client import create_test_http_client


def test_user_sdk_create_user():
    test_http_client = create_test_http_client("createUser")

    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("PETSTORE_API_KEY", "value"),
    ) as p_client:
        assert p_client is not None

        res = p_client.user.create_user(
            request={
                "id": 10,
                "username": "theUser",
                "first_name": "John",
                "last_name": "James",
                "email": "john@email.com",
                "password": "12345",
                "phone": "12345",
                "user_status": 1,
            }
        )
        assert res is not None
        assert res == models.User(
            id=10,
            username="theUser",
            first_name="John",
            last_name="James",
            email="john@email.com",
            password="12345",
            phone="12345",
            user_status=1,
        )


def test_user_sdk_create_users_with_list_input():
    test_http_client = create_test_http_client("createUsersWithListInput")

    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("PETSTORE_API_KEY", "value"),
    ) as p_client:
        assert p_client is not None

        res = p_client.user.create_users_with_list_input(
            request=[
                {
                    "id": 10,
                    "username": "theUser",
                    "first_name": "John",
                    "last_name": "James",
                    "email": "john@email.com",
                    "password": "12345",
                    "phone": "12345",
                    "user_status": 1,
                },
            ]
        )
        assert res is not None
        assert res == models.User(
            id=10,
            username="theUser",
            first_name="John",
            last_name="James",
            email="john@email.com",
            password="12345",
            phone="12345",
            user_status=1,
        )


def test_user_sdk_login_user():
    test_http_client = create_test_http_client("loginUser")

    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("PETSTORE_API_KEY", "value"),
    ) as p_client:
        assert p_client is not None

        res = p_client.user.login_user()
        assert res is not None
        assert res.result is not None
        assert res.result == "<value>"


def test_user_sdk_get_user_by_name():
    test_http_client = create_test_http_client("getUserByName")

    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("PETSTORE_API_KEY", "value"),
    ) as p_client:
        assert p_client is not None

        res = p_client.user.get_user_by_name(username="Edyth10")
        assert res is not None
        assert res == models.User(
            id=10,
            username="theUser",
            first_name="John",
            last_name="James",
            email="john@email.com",
            password="12345",
            phone="12345",
            user_status=1,
        )


def test_user_sdk_delete_user():
    test_http_client = create_test_http_client("deleteUser")

    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("PETSTORE_API_KEY", "value"),
    ) as p_client:
        assert p_client is not None

        res = p_client.user.delete_user(username="Rita_Schuppe")
        assert res is not None
        assert res == models.User(
            id=10,
            username="theUser",
            first_name="John",
            last_name="James",
            email="john@email.com",
            password="12345",
            phone="12345",
            user_status=1,
        )
