"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from petstore.errors import PetstoreError
from petstore.types import BaseModel
from typing import Optional


class APIErrorInvalidInputData(BaseModel):
    status: int

    error: str


class APIErrorInvalidInput(PetstoreError):
    r"""Not Found error"""

    data: APIErrorInvalidInputData

    def __init__(
        self,
        data: APIErrorInvalidInputData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
